### ISSUE TITLE
Why am I getting npm install errors?

### ISSUE THREAD

**Issue by CODe1995** [QingdaoU/OnlineJudgeFE#108]
# Permission error occurs when `sudo npm install` on Ubuntu 18.04
It was solved by modifying the permissions of that path.
But I don't know why the error occurs despite `sudo npm install`.

### OS environment
```
*AWS EC2 Ubuntu*
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```
  
### npm error screenshot
![image](https://user-images.githubusercontent.com/47562093/133456569-e4fac5b2-de48-4433-a94a-8b955969ce8e.png)

### npm error logs
```bash
15503 verbose stack Error: Command failed: git clone --mirror -q git://github.com/itargaryen/simple-hotkeys.git /home/ubuntu/.npm/_cacache/tmp/git-clone-20ea6e5d/.git
15503 verbose stack /home/ubuntu/.npm/_cacache/tmp/git-clone-20ea6e5d/.git: Permission denied
15503 verbose stack
15503 verbose stack     at ChildProcess.exithandler (child_process.js:281:12)
15503 verbose stack     at emitTwo (events.js:126:13)
15503 verbose stack     at ChildProcess.emit (events.js:214:7)
15503 verbose stack     at maybeClose (internal/child_process.js:915:16)
15503 verbose stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
15503 verbose stack     at emitOne (events.js:116:13)
15503 verbose stack     at Socket.emit (events.js:211:7)
15503 verbose stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
15504 verbose cwd /home/ubuntu/OnlineJudgeFE
15505 verbose Linux 5.4.0-1045-aws
15506 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
15507 verbose node v8.17.0
15508 verbose npm  v6.13.4
15509 error code 1
15510 error Command failed: git clone --mirror -q git://github.com/itargaryen/simple-hotkeys.git /home/ubuntu/.npm/_cacache/tmp/git-clone-20ea6e5d/.git
15510 error /home/ubuntu/.npm/_cacache/tmp/git-clone-20ea6e5d/.git: Permission denied
15511 verbose exit [ 1, true ]
```

**Comment by CODe1995** [comment]
I solved it by modifying the directory permissions, and there was no response for a long time, so I closed the issue.
