### ISSUE TITLE
超级报错，前端咋也运行不了

### ISSUE THREAD

**Issue by gaiteve** [QingdaoU/OnlineJudgeFE#120]
> 

> 我没有改前端，但是疯狂报错
PS G:\OnlineJudgeFE-master> npm run dev

> onlinejudge@2.0.0 dev G:\OnlineJudgeFE-master
> node build/dev-server.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\OnlineJudgeFE-master\build\check-versions.js:2:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! onlinejudge@2.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the onlinejudge@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     G:\node-v8.1.2-win-x64\node_cache\_logs\2022-10-24T23_53_22_107Z-debug.log

help me~!

**Comment by JunLiangWangX** [comment]
![image](https://user-images.githubusercontent.com/40155337/218042405-02b791b0-669a-462f-991d-8b361ed80460.png)
node版本切换到8.12.0，并按照文档构建

**Comment by Harry-zklcdc** [comment]
升级`node`到14（16也可以试试，14目前可以使用）吧。然后升级`npm`(`npm install npm --upgrade`)
