### ISSUE TITLE
npm install时 出错 Host key verification failed.

### ISSUE THREAD

**Issue by eon-wu-zhenxiong** [QingdaoU/OnlineJudgeFE#121]
# 环境
ubuntu 18.04
win 10
win 11 
上均尝试了

# 已安装 node v8.12.0

# 问题
## 命令：
```
E:\wzx\Vueproject\OnlineJudgeFE>E:\wzx\nvm\v8.12.0\npm install
```
## 报错
```
npm ERR! Error while executing:
npm ERR! E:\program files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/itargaryen/simple-hotkeys.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\白板\AppData\Roaming\npm-cache\_logs\2022-11-20T15_20_27_606Z-debug.log
```

## 日志
```
2481 verbose stack     at Socket.emit (events.js:211:7)
2481 verbose stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
2482 verbose cwd E:\wzx\Vueproject\OnlineJudgeFE
2483 verbose Windows_NT 10.0.22000
2484 verbose argv "E:\\wzx\\nvm\\v8.12.0\\node.exe" "E:\\wzx\\nvm\\v8.12.0\\node_modules\\npm\\bin\\npm-cli.js" "install"
2485 verbose node v8.12.0
2486 verbose npm  v6.4.1
2487 error Error while executing:
2487 error E:\program files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/itargaryen/simple-hotkeys.git
2487 error
2487 error Host key verification failed.
2487 error fatal: Could not read from remote repository.
2487 error
2487 error Please make sure you have the correct access rights
2487 error and the repository exists.
2487 error
2487 error exited with error code: 128
2488 verbose exit [ 1, true ]
```

**Comment by JunLiangWangX** [comment]
错误信息为验证失败，应该是网络问题导致的，我尝试翻墙下载该问题解决了
