### ISSUE TITLE
I'm failing to install FE (about node_env setting)

### ISSUE THREAD

**Issue by eagle705** [QingdaoU/OnlineJudgeFE#26]
I'm trying to install FE, but it doesn't work
I already use ```node install```command and I'm using node v6.11. 
few days ago, this command work but it isn't now. 
is it related about updating source (new commit) ? 

```
 eagle@eagle-1  ~/workspace/OnlineJudgeFE-master  NODE_ENV=development npm run build:dll

> onlinejudge@2.0.0 build:dll /Users/eagle/workspace/OnlineJudgeFE-master
> webpack --config=build/webpack.dll.conf.js

fatal: Not a git repository (or any of the parent directories): .git
child_process.js:515
    throw err;
    ^

Error: Command failed: git rev-parse HEAD
fatal: Not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:472:13)
    at Object.execSync (child_process.js:512:13)
    at Object.<anonymous> (/Users/eagle/workspace/OnlineJudgeFE-master/config/dev.env.js:2:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eagle/workspace/OnlineJudgeFE-master/config/prod.env.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 17.3.0
npm ERR! argv "/Users/eagle/.nvm/versions/node/v6.11.5/bin/node" "/Users/eagle/.nvm/versions/node/v6.11.5/bin/npm" "run" "build:dll"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! onlinejudge@2.0.0 build:dll: `webpack --config=build/webpack.dll.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the onlinejudge@2.0.0 build:dll script 'webpack --config=build/webpack.dll.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the onlinejudge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config=build/webpack.dll.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs onlinejudge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls onlinejudge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eagle/workspace/OnlineJudgeFE-master/npm-debug.lo
```

**Comment by eagle705** [comment]
This is ```npm-debug.lo```

```
  1 0 info it worked if it ends with ok
  2 1 verbose cli [ '/Users/eagle/.nvm/versions/node/v6.11.5/bin/node',
  3 1 verbose cli   '/Users/eagle/.nvm/versions/node/v6.11.5/bin/npm',
  4 1 verbose cli   'run',
  5 1 verbose cli   'build:dll' ]
  6 2 info using npm@3.10.10
  7 3 info using node@v6.11.5
  8 4 verbose run-script [ 'prebuild:dll', 'build:dll', 'postbuild:dll' ]
  9 5 info lifecycle onlinejudge@2.0.0~prebuild:dll: onlinejudge@2.0.0
 10 6 silly lifecycle onlinejudge@2.0.0~prebuild:dll: no script for prebuild:dll, continuing
 11 7 info lifecycle onlinejudge@2.0.0~build:dll: onlinejudge@2.0.0
 12 8 verbose lifecycle onlinejudge@2.0.0~build:dll: unsafe-perm in lifecycle true
 13 9 verbose lifecycle onlinejudge@2.0.0~build:dll: PATH: /Users/eagle/.nvm/versions/node/v6.11.5/lib/node_modules/npm/bin/node-gyp-bin:/Users/eagle/workspace/OnlineJudgeFE-master/node_modules/.bin:/User    s/eagle/.nvm/versions/node/v6.11.5/bin:/Users/eagle/bin:/usr/local/bin:/usr/local/apache-maven/apache-maven-3.5.2/bin:/Users/eagle/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local    /Cellar/virtuoso/7.2.4.2/bin:/Users/eagle/neo4j-community-3.3.5/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin:/usr/local/mysql/bin
 14 10 verbose lifecycle onlinejudge@2.0.0~build:dll: CWD: /Users/eagle/workspace/OnlineJudgeFE-master
 15 11 silly lifecycle onlinejudge@2.0.0~build:dll: Args: [ '-c', 'webpack --config=build/webpack.dll.conf.js' ]
 16 12 silly lifecycle onlinejudge@2.0.0~build:dll: Returned: code: 1  signal: null
 17 13 info lifecycle onlinejudge@2.0.0~build:dll: Failed to exec build:dll script
 18 14 verbose stack Error: onlinejudge@2.0.0 build:dll: `webpack --config=build/webpack.dll.conf.js`
 19 14 verbose stack Exit status 1
 20 14 verbose stack     at EventEmitter.<anonymous> (/Users/eagle/.nvm/versions/node/v6.11.5/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
 21 14 verbose stack     at emitTwo (events.js:106:13)
 22 14 verbose stack     at EventEmitter.emit (events.js:191:7)
 23 14 verbose stack     at ChildProcess.<anonymous> (/Users/eagle/.nvm/versions/node/v6.11.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
 24 14 verbose stack     at emitTwo (events.js:106:13)
 25 14 verbose stack     at ChildProcess.emit (events.js:191:7)
 26 14 verbose stack     at maybeClose (internal/child_process.js:920:16)
 27 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
 28 15 verbose pkgid onlinejudge@2.0.0
 29 16 verbose cwd /Users/eagle/workspace/OnlineJudgeFE-master
 30 17 error Darwin 17.3.0
 31 18 error argv "/Users/eagle/.nvm/versions/node/v6.11.5/bin/node" "/Users/eagle/.nvm/versions/node/v6.11.5/bin/npm" "run" "build:dll"
 32 19 error node v6.11.5
 33 20 error npm  v3.10.10
 34 21 error code ELIFECYCLE
 35 22 error onlinejudge@2.0.0 build:dll: `webpack --config=build/webpack.dll.conf.js`
 36 22 error Exit status 1
 37 23 error Failed at the onlinejudge@2.0.0 build:dll script 'webpack --config=build/webpack.dll.conf.js'.
 38 23 error Make sure you have the latest version of node.js and npm installed.
 39 23 error If you do, this is most likely a problem with the onlinejudge package,
 40 23 error not with npm itself.
 41 23 error Tell the author that this fails on your system:
 42 23 error     webpack --config=build/webpack.dll.conf.js
 43 23 error You can get information on how to open an issue for this project with:
 44 23 error     npm bugs onlinejudge
 45 23 error Or if that isn't available, you can get their info via:
 46 23 error     npm owner ls onlinejudge
 47 23 error There is likely additional logging output above.
 48 24 verbose exit [ 1, true ]
```

**Comment by eagle705** [comment]
I found it .. it should install from git not zip file..
