### ISSUE TITLE
(node:25795) UnhandledPromiseRejectionWarning: Error: Exited with code 3

### ISSUE THREAD

**Issue by RedoC-github** [QingdaoU/OnlineJudgeFE#95]
# Error Code
(node:25795) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/home/redoc/OnlineJudgeFE/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12)
(node:25795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25795) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# How can I solve this problem?

**Comment by g0ink** [comment]
I also encountered the same problem, and finally solved it by using `node.js v8.12.0`
https://nodejs.org/download/release/v8.12.0/
